javascript-polygon Complete
code-squad/javascript-polygon pull request #1
Opened 2017-10-16 12:17 UTC by Eclatant

Lecture 관련 내용을 정리하여 PR 작성하였습니다.

리뷰 부탁드립니다...!

2017-10-17 01:50 UTC, nigayo commented
좋은 커밋메시지가 어떤것인지 알아보고, 본인이 규칙을 만들어서 어디에 올려두세요. 
스스로 그 규칙을 지켜봅니다.
커밋단위는 함수하나당 한커밋정도로 기능하나에 하나의 커밋으로 하세요.

2017-10-17 01:58 UTC, nigayo commented
코드는 코드대로 파일을만들고, 설명은 따로 markdown으로 작성하는 건 어때요?

2017-10-17 01:58 UTC, crongro requested changes
코멘트 모두 확인하고 다시 수정해보세요.

2017-10-17 01:58 UTC, nigayo commented on Eclatant/171016.md
> +  const arg = Array.prototype.slice.call(arguments, 1);
참고로 이런코드는 동작방식에 대해서 잘 설명할 수 있어야 합니다.

2017-10-17 01:58 UTC, nigayo commented on Eclatant/171016.md
> +    typeof numArr[2] !== "number"
함수로 분리하는건 어때요? 그리고 이것도 배열이면 loop를 도는게 좋을 듯. 만약 인자의 갯수가 3개이상이라면 또 수정되야 하는 코드이기도 하고요.

2017-10-17 01:58 UTC, nigayo commented on Eclatant/171016.md
> +  return numArr[0] * numArr[1] * numArr[2] / 2;
결과값을 변수에 담고나서 return 해주는게 디버깅에 더 유리할 거 같아요.

2017-10-17 03:23 UTC, Eclatant commented
@crong

말씀해주신 것처럼 코드를 별도 파일로도 생성해두었습니다...!

커밋 규칙은
- 제목 : 무엇을 수정했는가?
- 내용 : 왜 수정했는가?

를 담으면 좋겠다고 생각하였는데, 좀 더 리뷰를 받아가면서 규칙을 확립해보도록 하겠습니다.

다음 번 Lecture부터는 커밋에 좀 더 신경써보도록 하겠습니다!

2017-10-17 05:51 UTC, crongro requested changes
좀더 수정해보세요.

2017-10-17 05:51 UTC, nigayo commented on Eclatant/다각형을 계산하는 함수.js
> +function circle(radius) {
함수이름은 동사+명사 형태로.

2017-10-17 05:51 UTC, nigayo commented on Eclatant/다각형을 계산하는 함수.js
> +    return null;
return false 가 나아요. null은 object취급을 하는 특별한 값이라 javascript에서는 부정의미로 잘 안써요.

2017-10-17 05:51 UTC, nigayo commented on Eclatant/다각형을 계산하는 함수.js
> +  if (arguments.length !== 3) {
빨리 오류는 반환하는건 좋아보이네요.

2017-10-17 05:51 UTC, nigayo commented on Eclatant/만능함수와 디버깅.js
> +      return true;
true?

2017-10-17 05:51 UTC, nigayo commented on Eclatant/만능함수와 디버깅.js
> +  var result = Math.pow(numArr[0], 2) * Math.PI;
변수 이름하나에도  정확한 의미를 부여하기.

2017-10-17 05:51 UTC, nigayo commented on Eclatant/만능함수와 디버깅.js
> +function trapezoid(numArr) {
함수에 파라미터가 3개 필요하면, 3개를 선언하고 사용하는게 좋겠죠. 
배열로 받는것보다는 차라리 object가 나은데, 지금은 3개의 파라미터로 받는게 좋겠네요.

2017-10-18 08:03 UTC, crongro requested changes
좀더~

2017-10-18 08:03 UTC, nigayo commented on Eclatant/다각형을 계산하는 함수.js
> +  var reacArea = base * height;
변수초기화는 가급적 함수 윗부분에서 합니다.

2017-10-18 08:03 UTC, nigayo commented on Eclatant/배열을 이용한 로깅.js
> +  }
오류체크만 하는 함수를 따로 만들어 볼래요?

2017-10-18 08:03 UTC, nigayo commented on Eclatant/파라미터를 체크하는 다각형의 넓이 함수.js
> +    return null;
null 을 많이 썻는데 그냥 return; 해도 될 듯.

2017-10-19 03:47 UTC, nigayo commented
요번엔 merge pull request 를 해봤어요 ~

2017-10-19 03:47 UTC, merged