Amorfati0310
code-squad/javascript-polygon pull request #10
Opened 2018-03-06 08:47 UTC by amorfati0310

arguments 가  caculateCircleSized에서는 getArea에서는 값이 없을 때는 undefined가 뜨고 
그냥caculateCircleSize만  호출하고  arguments로 불렀을 때는 매개변수가 하나일때는 {undefined는 호출이 되지 않고 불려지지 않는데 } 어떻게 2방식 모두 동작하도록 변화를 주어야 할지 잘 모르겠습니다

2018-03-06 09:32 UTC, crongro requested changes
함수,arguments, es6문법등을 어느정도 이해하고 계시네요.

에러처리가 좀 복잡해보입니다.
calculateCircleSize 함수안에서 해야하는 일들(체크해야할일들)을 글(말)로 표현해볼래요?  어떤 순서로 무엇을 체크해야하는지.

2018-03-06 09:32 UTC, nigayo commented on index.js
> +        console.log('최소 한가지 값이 필요합니다');
메시지를 보고 isAllUndefined 함수의 동작을 상상해보면, ' arguments의 길이가 0인지 확인' 만 하면 되는거 아닌가요?

2018-03-06 09:32 UTC, nigayo commented on index.js
> +        console.log('최소 한가지 값이 필요합니다');
그리고 이런상황에서는 뒤에 else문을 쓰지 않고, 여기서 함수를 바로 탈출하면 어떨까요?

2018-03-06 09:32 UTC, nigayo commented on index.js
> +let isNumber = item => {return typeof item === "number"}
지금은 한줄짜리는 함수로 나누지 않고 코드에서 그대로 보여주는게 더 잘 읽히는 거 같아요.
이런코드까지는 아직 함수로 나누지 말고 짜보죠.

2018-03-07 08:48 UTC, crongro requested changes
구두로 말씀드린것처럼 좀 쉽게 짜는 방법을 같이 찾아봅시다.

2018-03-08 08:26 UTC, crongro requested changes
코드가 좋아졌네요.
ES6문법 이해도도 좋고요.

조금 더 수정해보죠.

2018-03-08 08:26 UTC, nigayo commented on refactoring.js
> +const calculateErrorText = {
적당히 이름을 줄여보죠. ErrorText 정도는 어때요?

2018-03-08 08:26 UTC, nigayo commented on refactoring.js
> +const calculateErrorText = {
메시지를 이렇게 객체로 묶어둔 건 좋아요.

2018-03-08 08:26 UTC, nigayo commented on refactoring.js
> +    if(typeof data == "number"){
비교는 항상 === 
==와의 차이는 알고 있어야 하고요.

2018-03-08 08:26 UTC, nigayo commented on refactoring.js
> +        reportList.push('circle')
구현한걸 보니까 제가 낸 문제를 수정하고 싶은게 보이네요. ㅎ

printCouts함수와 repostList 를 합쳐서 데이터구조를 만들고 값을 증가/추가 할 수 있을까요?

2018-03-08 08:26 UTC, nigayo commented on refactoring.js
> +            getTrapeSize(inspectValidData(args[0]),inspectValidData(args[1]),inspectValidData(args[2]))
이렇게도 가능하겠네요.
getTrapeSize(inspectValidData.slice(0,3));

2018-03-09 01:40 UTC, crongro requested changes
잘 하셨어요.

dail 가 ES5로 코딩하는 걸 확인해보고 싶은데요. 
이번에 한번만, ES5로 수정시도를 한번 해보시죠. 
(너무 괴로워마시길)

아래 내용을 사용하지 않고 해보세요.
const/let
arrow function
template literal
rest parameter 
spread operator .

2018-03-12 10:22 UTC, crongro approved these changes
리뷰내용은 참고하시고요. approve 합니다. 
다음 미션도 ES5로 한번더 구현해보세요.

2018-03-12 10:22 UTC, nigayo commented on refactoring.js
> +var ArgumentstoArray = function(arguments) {
arguments 는 원래 함수에 숨겨져서 생성되는 매개변수에요.

2018-03-12 10:22 UTC, nigayo commented on refactoring.js
> +var ArgumentstoArray = function(arguments) {
이거 일부러 만든거죠? 
Array.prototype.slice.call 이라는 메서드로 만들수도 있긴해요.
직접 만든 시도는 좋네요.

2018-03-12 10:23 UTC, merged

2018-03-12 11:16 UTC, amorfati0310 commented
네엡 감사합니다 ~~ :)

2018. 3. 12. 오후 7:22에 "nigayo" <notifications@github.com>님이 작성:

> *@nigayo* approved this pull request.
>
> 리뷰내용은 참고하시고요. approve 합니다.
> 다음 미션도 ES5로 한번더 구현해보세요.
> ------------------------------
>
> In refactoring.js
> <https://github.com/code-squad/javascript-polygon/pull/10#discussion_r173746325>
> :
>
> > -        case 0: throw new Error(ErrorText.noArguments);
> -        case 1,2: throw new Error(ErrorText.insufficientArguments);
> -        case 3: return printResult(
> -            printText,
> -            getTrapeSize(...inspectValidAllData(...args).slice(0,3))
> -        )
> -        break;
> -    }
> -}
> +var Type = {
> +  Circle: "circle",
> +  Rect: "rect",
> +  Trape: "trape"
> +};
> +
> +var ArgumentstoArray = function(arguments) {
>
> arguments 는 원래 함수에 숨겨져서 생성되는 매개변수에요.
> ------------------------------
>
> In refactoring.js
> <https://github.com/code-squad/javascript-polygon/pull/10#discussion_r173746814>
> :
>
> > -        case 0: throw new Error(ErrorText.noArguments);
> -        case 1,2: throw new Error(ErrorText.insufficientArguments);
> -        case 3: return printResult(
> -            printText,
> -            getTrapeSize(...inspectValidAllData(...args).slice(0,3))
> -        )
> -        break;
> -    }
> -}
> +var Type = {
> +  Circle: "circle",
> +  Rect: "rect",
> +  Trape: "trape"
> +};
> +
> +var ArgumentstoArray = function(arguments) {
>
> 이거 일부러 만든거죠?
> Array.prototype.slice.call 이라는 메서드로 만들수도 있긴해요.
> 직접 만든 시도는 좋네요.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/code-squad/javascript-polygon/pull/10#pullrequestreview-102983568>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYBayu7hJG3TI7fhArFLT9KZphm1p77gks5tdkx_gaJpZM4SeUBQ>
> .
>