Update README.md 및index.js 코드 초기화
code-squad/javascript-polygon pull request #16
Opened 2018-03-08 08:22 UTC by antaehyeon

- Update README.md
- index.js 코드 초기화

2018-03-09 01:56 UTC, crongro requested changes
인자 체크를 꼼꼼하게 하신 거 같네요.
좀더 수정해보시죠.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +    if (arguments.length === 0)
if/else를 사용할때 {}를 항상 사용하도록 해보세요.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +        let lastData = arguments[1];
이런 변수 선언은 보통 함수위쪽이나, 지금은 조건문 위쪽(else if 다음)에 선언해두는 게 일반적입니다.
중간에 선언하면 사용될 변수들이 잘 드러나지 않을 수 있어서요.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +    calledFunctionCount++;
값을 추가하고, 배열에 추가한 건 좋은데요.
생각해볼만 건, 이 부분이 함수가 잘 실행됐을때 처리해야 하는 것인지, 
아니만 함수의 정상처리를 떠나서 무조건 실행되는 것인지, 
를 결정하고 사용해야겠네요.

지금은 무조건 실행되는 코드니까, 의도한 게 맞다면 잘 하셨고요.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +    if (typeof(lowerbase) === "number" && typeof(upperbase) && typeof(height) === "number")
typeof(upperbase) 중간에 이건 이상한데요. 비교하는 게 없네요.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +    calledFunctionSequence.forEach(value => console.log(value));
arrow 함수는 es6기능입니다. 잘 이해하고 사용하세요~
forEach도 마찬가지고요.

2018-03-09 01:56 UTC, nigayo commented on index.js
> +    if (typeof(width) === "number" && typeof(height) === "number")
이렇게 동작하는 isAllNumber 함수를 만들어보실래요? 

if( isAllNumber([width, height]) ) 
if( isAllNumber([width]) )
if( isAllNumber([width, height, otherValue]) )

2018-03-12 03:58 UTC, antaehyeon commented on index.js
> +    if (arguments.length === 0)
확인하였습니다 👍

2018-03-12 03:58 UTC, antaehyeon commented on index.js
> +        let lastData = arguments[1];
확인하였습니다 👍

2018-03-12 03:59 UTC, antaehyeon commented on index.js
> +    calledFunctionCount++;
이 부분이 혹시 calledFunctionCount 가 증가하는 부분을 말씀하신 건가요?

2018-03-12 03:59 UTC, antaehyeon commented on index.js
> +    if (typeof(lowerbase) === "number" && typeof(upperbase) && typeof(height) === "number")
확인하였습니다 👍

2018-03-12 03:59 UTC, antaehyeon commented on index.js
> +    calledFunctionSequence.forEach(value => console.log(value));
ES5 와 ES6의 차이에 대해서 명확하게 짚어가면서 코딩하도록 하겠습니다 👍

2018-03-12 05:37 UTC, antaehyeon commented on index.js
> +    if (typeof(width) === "number" && typeof(height) === "number")
확인하였습니다. 새로 Push 하도록 하겠습니다 👍

2018-03-12 05:51 UTC, antaehyeon commented
피드백을 반영한 코드를 Push 하였습니다 :)

2018-03-12 09:56 UTC, crongro requested changes
리뷰적었네요.

2018-03-12 09:56 UTC, nigayo commented on index.js
>      if (arguments[0] <= 0 || arguments[1] <= 0)
calCircleArea 함수에서, 오류 상황은 함수초반에 모아서, 빨리 반환처리하는 게 좋겠어요.

2018-03-12 09:56 UTC, nigayo commented on index.js
> +            correctNum++;
count를 세지 않고도 할 수 있을 거 같아요. 문제가 되면 바로 return!

2018-03-13 07:36 UTC, antaehyeon commented on index.js
> +            correctNum++;
코드를 생각나는대로만 작성해버렸네요.
앞으로 한번 더 확인하는 습관을 가지도록 하겠습니다.
확인하였습니다 👍

2018-03-13 07:36 UTC, antaehyeon commented on index.js
>      if (arguments[0] <= 0 || arguments[1] <= 0)
확인하였습니다 👍

2018-03-14 09:56 UTC, crongro approved these changes
수고했어요.

2018-03-14 09:56 UTC, merged