다각형의 넓이 #1
code-squad/javascript-polygon pull request #17
Opened 2018-03-09 06:01 UTC by sejungkim

다각형의 넓이 첫번째 버전입니다.

2018-03-09 06:32 UTC, crongro requested changes
함수구분을 잘 했어요. 
리뷰반영해보세요.

2018-03-09 06:32 UTC, nigayo commented on index.js
> +    if(inputVal.length !== validNum) {
짧은 내용임으로 3항연산자를 써보세요.

2018-03-09 06:32 UTC, nigayo commented on index.js
> +        return console.log("1개의 인자가 필요합니다.");
console.log 결과를 return 하는건가요?  return이 필요할까요?

2018-03-09 06:32 UTC, nigayo commented on index.js
> +function checkNumberOfInput(validNum, inputVal) {
validNum 아이디어는 좋네요.

2018-03-09 06:39 UTC, sejungkim commented on index.js
> +        return console.log("1개의 인자가 필요합니다.");
함수의 종료를 명시적으로 보여주려고 그랬던건데, 없는게 나을까요?

2018-03-09 06:39 UTC, sejungkim commented on index.js
> +function checkNumberOfInput(validNum, inputVal) {
감사합니다!

2018-03-09 07:16 UTC, sejungkim commented
리뷰 반영 했습니다.

2018-03-12 01:07 UTC, crongro approved these changes
프로그램이 실행되다가 오류가 생기면, 프로그램을 멈추고 오류를 뱉어야 하는 경우가 생길 수 있어요.
지금은 오류가 아니죠.

그럴때는 
 throw "숫자가 필요해요";  이렇게도 합니다.

지금 구현한것과 차이점을 확인해보세요.

2018-03-12 01:07 UTC, merged