Youngdo212
code-squad/javascript-polygon pull request #18
Opened 2018-03-09 10:01 UTC by youngdo212

2018-03-12 01:33 UTC, crongro requested changes

2018-03-12 01:33 UTC, nigayo commented on 180307_polygonArea.js
> +                console.log("숫자형 타입만 계산이 가능합니다");
여기서 오류내용을 반환하거나, 오류를 발생시켜서 프로그램을 멈추게 하는 게 나을 거 같아요.

즉,
return을 하거나, 
throw를 하거나.

2018-03-14 09:58 UTC, crongro requested changes
git 충돌시 어떻게 소스코드를 수정해야 하는지 알아보세요~

2018-03-14 09:58 UTC, nigayo commented on 180307_polygonArea.js
> +<<<<<<< HEAD
충돌을 해결하지 않고 보내셨???

2018-03-16 02:11 UTC, crongro requested changes
타입과 인자체크가 꼼꼼하게 했네요.
실제로 모든 함수에서 이렇게하진 않겠지만요.

질문은 답변해주시고, 
리뷰참고하세요.

다음스텝으로 가보세요.

2018-03-16 02:11 UTC, nigayo commented on 180307_polygonArea.js
> +    switch(arguments.length){
실제로는 아래처럼 파라미터를 지정하는게 일반적이겠죠. 
function circleArea(radius){ }

파라미터 없이 코딩하는건 좋지 않을 겁니다. 참고하세요.

2018-03-16 02:11 UTC, nigayo commented on 180307_polygonArea.js
> +let getArea = (function(){
이렇게 즉시함수를 실행한 이유가 뭐에요? 큰 장점이 안보이는데 궁금하네요.

2018-03-16 05:48 UTC, youngdo212 reviewed
함수를 기능별로 분할하였습니다

2018-03-16 05:48 UTC, youngdo212 commented on 180307_polygonArea.js
> +let getArea = (function(){
클로저를 사용하기 위해 제작한 함수를 즉시실행 하였는데요. 이 함수 사용이 일회성에 그칠것 같아 따로 선언은 안해줬습니다. 이름 짓는게 어렵기도 하구요.

2018-03-19 01:39 UTC, crongro requested changes
수정해보세요.

2018-03-19 01:39 UTC, nigayo commented on 180307_polygonArea.js
> +    if(!validLength.includes(arr.length)) throw "올바른 인자 개수를 입력하십시오";
includes 함수의 브라우저 호환성을 알아보세요.
지원하지 않는 브라우저에서는 어떻게 처리할 수 있을까요?

2018-03-19 01:39 UTC, nigayo commented on 180307_polygonArea.js
> +    for(let radius = start; radius <= end; radius++){
reduce 를 써서 for문을 대신해볼래요?

2018-03-19 01:39 UTC, nigayo commented on 180307_polygonArea.js
> +    checkError(Array.from(arguments), 1, 2);
arguments 자체를 전달하기보다는, 배열로 변경하고 그 값을 활용.

2018-03-19 02:59 UTC, youngdo212 commented on 180307_polygonArea.js
> +    if(!validLength.includes(arr.length)) throw "올바른 인자 개수를 입력하십시오";
인터넷 익스플로러(데스크탑버전)에서 include 메소드를 지원하지 않습니다(모바일은 가능).
모든 브라우저에서 지원하는 indexOf메소드를 이용할 수 있습니다.

2018-03-20 00:56 UTC, nigayo commented on 180307_polygonArea.js
> +    if(!validLength.includes(arr.length)) throw "올바른 인자 개수를 입력하십시오";
includes 코드를 그대로 사용하면서, 하위호환성을 보장하는 방법은 무엇일까요? 
polyfill 이란 무엇인지 찾아보고 다시 적용해보세요.

2018-03-20 00:58 UTC, crongro requested changes
약간 어려운 미션포함해서~

2018-03-20 00:58 UTC, nigayo commented on 180307_polygonArea.js
> +    return result.reduce((previous, current) => [...previous, getACircleArea(current)], []);
reduce를 직접 한번 구현해보세요.
그리고 현재 코드를 본인이 구현한 코드로 대치해보세요. (화이팅)

2018-03-23 02:24 UTC, crongro requested changes
이런, 
모르는 코드를 구현하지 마세요.

includes 는 직접 아는 범위내에서 구현해서 추가해주세요.

2018-03-26 02:21 UTC, crongro approved these changes
네. 이렇게 커스트마이징하게 만든 함수들은 
학습용으로 저장해두었다가 미션을 할때마다 재사용해서 써보세요.

문제를 발견하게 되고, 필요하면 기능을 추가하고 그러면서 함수활용도가 더 높아질 수 있을거에요.

2018-03-26 02:22 UTC, merged