다각형의 넓이 완료
code-squad/javascript-polygon pull request #19
Opened 2018-03-10 07:35 UTC by feanar729

2018-03-12 01:38 UTC, crongro requested changes
수정해보세요.

2018-03-12 01:38 UTC, nigayo commented on polygon.js
> +var errorComment = {
객체를 익혔나요? 
이렇게 에러메시지를 묶어서 관리하는 건 로직에서 데이터를 분리한 것이라 좋아요.

2018-03-12 01:38 UTC, nigayo commented on polygon.js
> +    if ((topSide <= 0 || bottomSide <= 0 || height <= 0) && typeof arguments === "number") {
아래처럼 처리하는 함수를 만들어서, 한번 조건문에서 호출해서 동작하게 해보세요.
(topSide <= 0 || bottomSide <= 0 || height <= 0)

2018-03-12 01:38 UTC, nigayo commented on polygon.js
> +    } else if ((typeof topSide !== "number" || typeof bottomSide !== "number" || typeof height !== "number") && arguments.length === 3) {
이것도 함수를 만들어서 호출해보죠.
(typeof topSide !== "number" || typeof bottomSide !== "number" || typeof height !== "number")

2018-03-13 06:40 UTC, feanar729 commented
피드백 반영해서 조건문을 함수로 만들었습니다.

2018-03-13 07:10 UTC, crongro requested changes
꼼꼼하게 체크하느라 수고했네요.
하지만 고칠것도 많군요 ㅎ

2018-03-13 07:10 UTC, nigayo commented on polygon.js
>              } else if (radius === null || radius === undefined || radius === " ") {
else if( !radius) 와는 어떤 차이가 있을까요?

2018-03-13 07:10 UTC, nigayo commented on polygon.js
>                      count++;
이름을 정확히 지어주세요. count는 무슨 count인지 알수없네요.

2018-03-13 07:10 UTC, nigayo commented on polygon.js
> +    } else if (conditionConfirm(bottomSide, height) === 'notNumber') {
이 함수는 왜 계속 여러번 호출되죠? 
conditionConfirm(bottomSide, height)

2018-03-13 07:10 UTC, nigayo commented on polygon.js
> +    } else if (bottomSide !== null && height) {
height 가 0이라면 false인데 괜찮나요?

2018-03-13 07:10 UTC, nigayo commented on polygon.js
> +    if (wantGetArea === "rect") {
switch 문으로 한번 수정해보세요.
if문이 더 적절한지 비교하면서 느껴보시고요.

2018-03-13 07:10 UTC, nigayo commented on polygon.js
> +    if ((typeof topSide === "string" || typeof bottomSide === "string" || typeof height === "string") && arguments.length === 3) {
이렇게 동작하는 함수를 만들어볼래요?
checkType(Array.from(arguments), "string")
checkType(Array.from(arguments), "number")

2018-03-17 07:00 UTC, feanar729 commented on polygon.js
>              } else if (radius === null || radius === undefined || radius === " ") {
이 방법은 미처 생각하지 못했습니다 감사합니다.

2018-03-17 07:00 UTC, feanar729 commented on polygon.js
>                      count++;
수정 했습니다.

2018-03-17 07:00 UTC, feanar729 commented on polygon.js
> +    if (wantGetArea === "rect") {
다수의 조건문 일때는 switch가 더 효율적이군요

2018-03-17 07:01 UTC, feanar729 commented on polygon.js
> +    } else if (bottomSide !== null && height) {
수정했습니다

2018-03-17 07:49 UTC, feanar729 reviewed
피드백을 반영해 다시 제작해보았습니다

2018-03-17 07:49 UTC, feanar729 commented on polygon.js
> +    if ((typeof topSide === "string" || typeof bottomSide === "string" || typeof height === "string") && arguments.length === 3) {
아 이런 방법도 있겠군요. 제 나름대로 다르게 시도해 제작해 보았습니다

2018-03-19 02:35 UTC, crongro approved these changes
오프라인 리뷰 기억하고 다음과제 해보죠.

2018-03-19 02:35 UTC, merged