[새라] 파라미터를 체크하는 다각형의 넓이 함수
code-squad/javascript-polygon pull request #21
Opened 2018-03-12 08:53 UTC by sejungkim

'파라미터를 체크하는 다각형의 넓이 함수' 완료했습니다.

2018-03-12 10:00 UTC, crongro requested changes
좀 어려운 미션 하나 드렸네요.
every..

2018-03-12 10:00 UTC, nigayo commented on index.js
> +        console.log(e);
console 객체에 log함수 말고 다른 함수도 있어요. 지금은 그걸쓰는 게 나을 거 같네요.

2018-03-12 10:00 UTC, nigayo commented on index.js
> +    try {
throw를 받아서 try/catch로 처리하는 건 좋은데요.
try/catch가 꼭 필요하진 않아요. 
보통 그냥 throw만 하곤 합니다. (콘솔창에 에러가 나타납니다)

2018-03-12 10:00 UTC, nigayo commented on index.js
> +    if(!inputValArray.every(elem => toString.call(elem) === "[object Number]")) {
toString.call이 무엇인지 잘 알아보세요.

every 함수를 직접 한번 만들어보실래요?  아래처럼 동작되면 됩니다.
every(inputValArray,  (elem) => toString.call(elem) === "[object Number]");

2018-03-13 05:56 UTC, sejungkim commented
리뷰 반영 했습니다.
- toString.call 대신 typeof 사용했습니다.
- every 메소드 대신 checkEvery함수를 만들어 반영했습니다.
- try/catch 없애고 throw만 사용했습니다.
- console.log 대신 console.error 를 사용해도 되지만 try/catch를 지워서 console 함수도 없앴습니다.

2018-03-13 06:43 UTC, crongro approved these changes
checkEvery 만 좀더 수정해두세요.
approve 합니다.

2018-03-13 06:43 UTC, nigayo commented on index.js
> +        if(funcName(targetArr[i])) {
오~ checkEvery 구현 했네요~ 

그런데 if/else 문은 좀더 줄여서 쓸 수 있겠는데요? 

if(!뭐시기냐()) return false;

2018-03-13 06:43 UTC, nigayo commented on index.js
>      if(inputValArray.length === 0) {
이건 어때요?  
!(inputValArray.length)

2018-03-13 06:57 UTC, sejungkim commented
수정 했습니다!

2018-03-13 07:00 UTC, merged

2018-03-13 07:00 UTC, nigayo commented
이건 머지 했어요. 다시 기능추가 후 pr!