[새라] 여러 함수를 호출하는 함수
code-squad/javascript-polygon pull request #23
Opened 2018-03-14 03:08 UTC by sejungkim

'여러 함수를 호출하는 함수' 완료했습니다.

2018-03-14 10:25 UTC, crongro requested changes
화살표에 빠지셨군요~ 좀더 수정해보세요.

2018-03-14 10:25 UTC, nigayo commented on index.js
> +    if(validNum !== (inputValArray.filter(elem => elem !== undefined)).length) {
아 이런 생각을 하다니 ㅎㅎ 재밌네요.

이 부분을 함수로 띠어내고 그걸 호출하는 건 어때요? 
조건문안에 있으니 좀 보기 어렵네요. 매번 이렇게 써야 할 거 같고요.
validNum !== (inputValArray.filter(elem => elem !== undefined)).length

2018-03-14 10:25 UTC, nigayo commented on index.js
> +            v2 = (v2 === undefined ? 1 : v2);
임의로 1을 할당한 이유는 뭐에요?

2018-03-14 10:25 UTC, nigayo commented on index.js
>      return true;
return true를 해줄 필요가 있나요?

2018-03-15 09:30 UTC, sejungkim commented on index.js
> +            v2 = (v2 === undefined ? 1 : v2);
getArea에서 'circle' 일때 두번째 인자값이 없으면 1번만 계산, 아니면 입력된 횟수만큼 계산하도록 구현하려고 그랬습니당

2018-03-16 09:58 UTC, sejungkim commented
리뷰 반영 했습니다.
- 각 계산 함수의 return true 삭제
- numberOfInput 함수 만들어서 입력된 값 중 undefined 제외한 값의 개수 체크해서 사용
- 삼항연산자 부분 if-else로 변경 (뭐가 더 나은건지 잘 모르겠습니다.)

2018-03-19 02:54 UTC, crongro approved these changes
checkEvery 함수처럼 함수를 인자로 받는 함수 활용을 잘 기억해서 나중에도 이렇게 구현해보세요.

checkInputValue 함수는 나중에도 다른 프로젝트에서 재사용할 수 있게 잘 보관해서 써보죠. 

수고했음요.

2018-03-19 02:54 UTC, crongro commented on index.js
> +            v2 = (v2 === undefined ? 1 : v2);
괄호가 좀 어색한데요. 보통은 이렇게 묶을 거 같아요.
v2 = (!v2) ? 1 : v2;

2018-03-19 02:54 UTC, merged