[새라] 배열을 이용한 로깅
code-squad/javascript-polygon pull request #24
Opened 2018-03-20 06:10 UTC by sejungkim

다각형의 넓이 - 배열을 이용한 로깅 완료입니다.

2018-03-21 00:18 UTC, crongro requested changes
코드가 괜찮은편입니다~

2018-03-21 00:18 UTC, nigayo commented on index.js
> +  return (targetArr.filter(elem => typeof elem !== 'undefined')).length;
return 뒤에 사용가능한  표현식은 짧으면 더 좋을거 같아요.  지금이 max정도 수준.
아래 결과를 받아서 그것을 return 하는정도가 좀더 나아보여요.
const result = targetArr.filter(elem => typeof elem !== 'undefined')
return result;

2018-03-21 00:18 UTC, nigayo commented on index.js
> +function getReport(collectValue) {
이 함수는 report를 get하는 함수지만, 실제 반환하는 코드가 없네요.

2018-03-21 00:18 UTC, nigayo commented on index.js
>          for (let i = 0; i < v2; i++) {
else 문 다음의 바로 이 for문은 살짝 아쉽네요.
switch - if  -for 문으로 이어지다보니 중첩된 코드가 됐고요.
작은 크기지만 함수를 하나더 만들어서 중첩을 한단계 줄여보세요.

2018-03-21 08:45 UTC, sejungkim commented
리뷰반영했습니다!
제 수정 내용에 크롱 의도가 잘 반영이 된 건지 모르겠네요..

- numberOfInput 함수의 return 표현을 짧게 수정했습니다.
- getReport 함수에 return 값을 추가했습니다.
- getArea 함수에 있던 for문을 함수로 빼서 사용했습니다.
- printReport 함수 만들었다가 생각해보니 특별히 필요한것 같지 않아서 다시 지웠습니다.

2018-03-21 09:02 UTC, nigayo commented
commit 로그에, 좀더 기능이 개선된거면, update로 시작하는 것도 좋아요.
fix는 보통 진짜 버그를 수정할때 사용하고요.

2018-03-21 09:10 UTC, crongro requested changes
코드 좋아지고 있어요.
조금 더 리뷰남겼는데, 생각해보시고, 잘 모르겠는 개념은 학습해보세요. 
필요한건 코드에 반영까지해보고요.

2018-03-21 09:10 UTC, nigayo commented on index.js
> +  return result;
함수의 구현이 짧고 처리할게 간단하다면 return 뒤에 쭉쓰는 것도 가능하긴하고요.
지금처럼 변수에 저장하고, 그 값을 반환하는 것도 보기좋고, 디버깅 하기도 좋아요(변수가 있어서 디버깅시 값 확인을 빨리 할 수 있음)

2018-03-21 09:10 UTC, nigayo commented on index.js
> +  if (!checkEvery(inputValArray, elem => typeof elem === 'number')) {
'를 쓸까 "를 쓸까는 개발자가 정해서 쓰면 되겠네요. 항상 같은 상황이면 같은 걸 쓰려는 노력이 중요하겠고요.

2018-03-21 09:10 UTC, nigayo commented on index.js
> +  checkInputValue([radius], 1);
1,2,3 .. 이런게 참 의미(의도)를 알기 어려운 코드네요. 
이런 코드는 어때요? 

```javascript
function checkInputValue(arr, {expectedValue}) {
   return arr.length === expectedValue;
}

checkInputValue([1,2], {expectedValue : 3});
```

2018-03-21 09:10 UTC, nigayo commented on index.js
> +      if (!v2) calculateCircle(v1);
네 전 보기좋네요~

2018-03-21 09:20 UTC, sejungkim commented on index.js
> +  return result;
아, 디버깅에 장점이 있었군용.. 감사합니다!

2018-03-21 09:21 UTC, sejungkim commented on index.js
> +  if (!checkEvery(inputValArray, elem => typeof elem === 'number')) {
원래 "를 사용했었는데 앞으로 '로 바꾸기로 했어요! shift 를 안 눌러도 되더라고요. ;)

2018-03-21 09:25 UTC, sejungkim commented on index.js
> +      if (!v2) calculateCircle(v1);
넵 저도 좋은것 같아요!
원래 처음에 함수로 뺄까 고민을 했었는데 너무 사소한것까지 함수로 만드는건가 싶기도 하고,
함수를 만드는 기준에 아직 확신이 없는 것 같아요.

2018-03-22 02:39 UTC, sejungkim commented
리뷰 반영이요~~!
- { expectedValue }
객체가 아직 익숙하지 않아서 생각하지 못했는데 알려주신 방식 마음에 들어서 반영해봤어요. 이렇게도 할 수 있구나- 하고 알게 되었습니당.
- 커밋메세지 피드백 감사해요! Update 적용해봤습니다. 영어로 써보는거 연습하는 중인데 어디서 주워들은 Fix만 열심히 썼네요. ㅋㅋㅋㅠㅠ

2018-03-23 01:26 UTC, crongro approved these changes
polygon 코드개선은 이쯤 해도 될 거 같아보입니다.

exptectedValue 는 이 설명을 통해서 제대로 이해해보세요.
http://2ality.com/2015/01/es6-destructuring.html#simulating-named-parameters-in-javascript

2018-03-23 01:26 UTC, merged