[Lecture1 - Step1] 다각형의 넓이
code-squad/javascript-polygon pull request #26
Opened 2018-09-12 05:02 UTC by Vanary

안녕하세요 crong! 

다각형의 넓이 첫 PR 입니다. 살펴보시고 피드백 부탁드립니다

2018-09-12 10:34 UTC, nigayo commented
커밋로그를 정성스럽게 작성하셨네요.

2018-09-12 10:40 UTC, crongro requested changes
DOM/EVENT를 제거하고 구현하기. 

함수인자를  잘 활용하시고요.

2018-09-12 10:40 UTC, nigayo commented on main.js
> +const computeArea = {
객체를 이해하고 썼군요. function글자를 지워도 됩니다.

 const a = {
  circle() {}
}

2018-09-12 10:40 UTC, nigayo commented on main.js
> +        return (circumference * height) + (2 * circleSize);
두 가지로 나눠서 구현한건 보기 좋고 디버깅때도 좋죠. 잘했어요.

2018-09-12 10:40 UTC, nigayo commented on main.js
> +        if (arr.some((num) => num <= 0)) {
(arr.some((num) => num <= 0) 이부분만 따로 함수로 빼볼래요?
이렇게까지 빼야할까? 싶지만 함수로 분리하면 조건문을 읽는데 더 수월해요.

2018-09-12 10:40 UTC, nigayo commented on main.js
> +            alert('입력하지 않은 정보가 있거나, 0보다 작거나 같은 값이 있습니다!');
alert보다는 console.log를 늘 쓰세요. 좋은UX도 아니라서요.

2018-09-12 10:40 UTC, nigayo commented on main.js
> +        const squareWidth = Number(document.getElementById('squareWidth').value);
dom을 통해서 입력받지 말고요, 
console에서 함수호출과함께 값을 입력받으세요.

2018-09-12 10:40 UTC, nigayo commented on main.js
> +circleSubmit.addEventListener("click", printArea.circle);
document.getElementById와 
addEventListener 를 쓰지 말고 구현해보세요.

2018-09-13 06:03 UTC, Vanary commented
살펴주신 내용 반영해 수정했습니다. 검토 부탁드립니다

2018-09-13 06:12 UTC, crongro approved these changes
수정 잘 했어요~
좀더 리뷰 남겨드려요

참고하시고요. 다음단계로 바로 진행하시죠.
리뷰내용은 다음단계하기 전에 수정하고 진행해주세요.
머지합니다.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +const printArea = {
객체리터럴 잘 하셨어요.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +    trapezoid(trapeTop, trapeBottom, trapeHeight, trapeArea) {
파라미터 이름들이 정확해서 좋습니다.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +        return arr.some((el) => (typeof el != "number")? true : false);
!! 가 뜻하는 게 뭔지 한번 찾아서 공부해보세요.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +    function elemNegativeOrZero(arr) {
반환값이 true/false 이면 보통 isNegative() 와 같은식으로 많이 구현합니다.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +        const inputArr = Array.from(arguments);
argList 라고 하는 것도 좋아보여요.
input은 사용자 입력을 뜻하는 경우가 좀더 많습니다.

2018-09-13 06:12 UTC, nigayo commented on main.js
> +        if(checkInputErr(inputArr, 2)) {return false;}
1,2 이렇게 인자로 주는게 어색하죠? 
object를 활용하면 이런부분을 좀더 직관적으로 바꿀 수 있습니다.

2018-09-13 06:12 UTC, merged

2018-09-13 07:28 UTC, Vanary commented on main.js
> +        return arr.some((el) => (typeof el != "number")? true : false);
Truthy / Falsy값들을 Boolean으로 바로 바꿔주는군요! 감사합니다.