first commit
code-squad/javascript-polygon pull request #27
Opened 2018-09-12 05:19 UTC by cohily12

2018-09-12 10:40 UTC, nigayo commented
브랜치이름은 그냥 step1 , step2 이렇게 하시면 됩니다. 
커밋로그는 좀 신경쓰셔야 할 거 같아요 ^^

2018-09-12 10:51 UTC, crongro requested changes
js특징을 잘 활용한 방법들이 돋보였어요.
리뷰남겨드리니 조금 더 수정해보시죠.

2018-09-12 10:51 UTC, nigayo commented on lecture1_step1.js
> +function isSame(fn, args){
이녀석은 여기저기서 많이 불리네요. 코드위치는 위쪽이 더 낫겠어요.

2018-09-12 10:51 UTC, nigayo commented on lecture1_step1.js
> +    if(fn.length !== args.length) throw new Error('인자의 개수를 확인하세요.');
fn.length 를 사용하다니.. 잘 했는데요. 
그런데 fn의 매개변수가 항상정확하다는 보장은 할 수 없을 거 같아요. 어떤 함수기 특별한 파라미터를 추가할 수도 있어서요.
하지만 지금 요구사항을 충족하기에는 좋은 아이디어에요.

2018-09-12 10:51 UTC, nigayo commented on lecture1_step1.js
> +    if(isSame(trapezoid, arguments) && isNum(...arguments)) return (a+b) * h / 2;
&& 연산자덕에 코드가 보기 좋아짐.

2018-09-12 10:51 UTC, nigayo commented on lecture1_step1.js
> +    Array.prototype.forEach.call(arguments, function(val){
Rest parameter 를 써보세요.

2018-09-12 10:51 UTC, nigayo commented on lecture1_step1.js
> +    if(isNum(...arguments)) {
여기서 false 조건을 판단해서 return해버리면, 코드가 어떻게 될까요?

2018-09-12 11:24 UTC, cohily12 commented on lecture1_step1.js
> +    if(fn.length !== args.length) throw new Error('인자의 개수를 확인하세요.');
crong! 바쁘신 와중에 리뷰 감사합니다. 아직 수정 전이지만 단순히 fn.length는 사용을 안하는 게 좋은 지 궁금합니다.

2018-09-12 12:37 UTC, nigayo commented on lecture1_step1.js
> +    if(fn.length !== args.length) throw new Error('인자의 개수를 확인하세요.');
표준속성인지 찾아보세요.
표준속성이 맞긴한데, 그닥 쓸모가 없는 셈이죠.

2018-09-13 08:05 UTC, crongro approved these changes
수정 잘 하셨어요.
다음부터는  브랜치이름도 step1, step2 이렇게 부탁드려요~
머지합니다.

2018-09-13 08:05 UTC, merged