1차 다각형넓이구하기
code-squad/javascript-polygon pull request #32
Opened 2018-09-13 03:22 UTC by alisonjh

2018-09-13 06:05 UTC, crongro requested changes
수고하셨어요!
낯선부분을 시도하고 적용하신 거 같아요.
잘하셨어요.

몇개 리뷰도 남겼으니 참고해서 수정해보세요
그리고 질문도 남겼습니다.
질문에 대답도 좀 해보세요~

2018-09-13 06:05 UTC, nigayo commented on step1.js
> +    if ([radius].length != arguments.length) {
이 비교가 의미하는 게 어떤거죠?

2018-09-13 06:05 UTC, nigayo commented on step1.js
> +function circleArea (radius) {
함수는 이름으로 무엇을 하는지 드러내야 합니다. 그래야 코드를 읽기 좋은데요.
주로 동사+명사로 표현해요.
그렇게 이름을 변경해보실래요?

2018-09-13 06:05 UTC, nigayo commented on step1.js
> +        let pi = 3.14;
let보다는 const가 더 잘 어울립니다! 왜그럴까요?

2018-09-13 06:05 UTC, nigayo commented on step1.js
> +        return console.log(result);
squareArea가 console.log의결과를 반환하고 있는데요. 의미가 없는 코드입니다.
console.log 의 반환값은 무엇인지 확인해보세요.

2018-09-13 06:05 UTC, nigayo commented on step1.js
> +    if ( isNaN(val) === true ) {
NaN이 의미하는게 뭔지 이해하고 계세요?

2018-09-13 07:37 UTC, alisonjh commented on step1.js
> +    if ([radius].length != arguments.length) {
인수의 개수 확인을 설계를 위한 문장이었습니다.

각 함수 안에서 let requireAugs = [radius];
와 같이 필수 인수를 array에 저장하고 값을 비교하는 방법이 나을까요?

하드코딩으로 변수를 저장해야되는 부분과 그렇지 않은 부분을 구분하는 게 어렵네요.
하드 코딩을 사용하지 않고,
함수를 설정할 때의 parameter의 length와 arguments의 length를 구분할 수는 없을까요?
인수의 개수를 확인 코드를 설계할 때 가장 궁금했던 점이어서 답변에도 덧붙여 봅니다.

2018-09-13 07:37 UTC, alisonjh commented on step1.js
> +function circleArea (radius) {
네 함수 이름 변경해서 push하겠습니다! :)

2018-09-13 07:38 UTC, alisonjh commented on step1.js
> +        let pi = 3.14;
pi는 절대 변하지 않을 값이니 상수인 const를 써야되네요! 이 부분도 수정하겠습니다 :)

2018-09-13 07:44 UTC, alisonjh commented on step1.js
> +    if ( isNaN(val) === true ) {
NaN는 Not a Number의 약자이며, isNaN() 메소드를 썼을 때 true값이 나오면 그 인자는 숫자가 아닌 그 여집합이다, 이렇게 이해하고 있었습니다. MDN에 가서 한 번 더 읽어보고 올게요!

2018-09-14 21:47 UTC, crongro approved these changes
수정사항 모두 확인했어요. 잘 하셨네요.
여기까지 승인/머지 합니다.
코드리뷰 가이드 다시보시면서, 이제 rebase받아서 다음 step브랜치 만들고 해보세요. ^^

아 그리고 
브랜치이름은  step001 말고 step1, step2로 해주시고요~

2018-09-14 21:47 UTC, merged