getArea method 구현
code-squad/javascript-polygon pull request #37
Opened 2018-09-13 11:40 UTC by cocoa-salon

객체를 이용하여 getArea 메소드를 정의하였습니다.

2018-09-14 02:37 UTC, crongro requested changes
완성이 되어가네요~ 잘했습니다.
리뷰남겨드리는 부분 수정해보세요.

2018-09-14 02:37 UTC, nigayo commented on getArea.html
> +            if ( arguments[0] !== "circle" && arguments[0] !== "rect" &&
const names = ["cicle", "rect", "trapezoid", "cylinder"];
이렇게 놓고 names 에 값이 있는지 없는지 체크하는방법을 해볼래요? 
지금보다 좀더 간단해질 거 같네요.

2018-09-14 02:37 UTC, nigayo commented on getArea.html
> +            this.count = 1; // 호출된 메소드 횟수 누적
count 이름을 좀더 구체적으로.

2018-09-14 02:37 UTC, nigayo commented on getArea.html
> +                this.getRectangleSize( arguments[1], arguments[2], arguments[3] );
arguments 이름이 좀더 길면.. 
짧은 이름 변수를 만들어서 arguments를 할당해서 쓸 수도 있죠.

2018-09-14 02:37 UTC, nigayo commented on getArea.html
> +            console.log("실행횟수: " + this.count );
count와 exName을 이렇게 해도 되는데요, 
배열 자료구조를 써보면 어떨지? 한번 바꿔보세요!

2018-09-14 02:57 UTC, cocoa-salon commented on getArea.html
> +            this.count = 1; // 호출된 메소드 횟수 누적
count 를 callCount로
exName을 callName으로 변경하였습니다.

2018-09-14 02:58 UTC, cocoa-salon commented on getArea.html
> +                this.getRectangleSize( arguments[1], arguments[2], arguments[3] );
arguments를 input 변수에 할당하였습니다.

2018-09-14 22:27 UTC, crongro requested changes
수정잘하셨네요.
몇개 리뷰남겨드리니 코드정리(마무리~) 해보세요!

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            if (input[0] === "circle" && input.length === 2) {
잘 수정했어요~

2018-09-14 22:27 UTC, nigayo commented on getArea.html
>              let upperSide = num;
num, num2 대신에 매개변수에 바로 upperSide, lowerSide로 선언하시면 되겠네요.
이렇게요.
function(upperSide, lowerSide, height) {...}

2018-09-14 22:27 UTC, nigayo commented on getArea.html
>          const getSize = {};
네임스페이스라고 합니다.
잘 사용해보신거 같아요. 이미 객체를 사용하고 계신거고요 .

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            debugger;
PR을 날릴때 디버깅용코드를 제거해보면서 보내보세요.
실제 서비스배포할때도(출시) 디버깅 코드는 없애거든요

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            if (this.callNames.includes(input[0]) !== true) {
if문은 자동으로 true/false를 판단해줍니다. 따라서 true와 비교할필요가 없어요.

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            this.callCountTotal += 1; // 총 메소드 호출횟수 누적
명확한이름! 굿

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            console.log(input); // 변환된 배열 확인
이코드도 디버깅용 코드라서,, 디버깅 확인작업이 끝나면 항상 없애버리세요~

2018-09-14 22:27 UTC, nigayo commented on getArea.html
> +            if (this.callNames.includes(input[0]) !== true) {
input[0]을 자주 부르고 있으니, 지역변수로 저장해두면 의미도 알기 좋고 더 성능좋은(배열을 뒤지지 않게되서)코드입니다.
const foo = input[0];

2018-09-17 02:52 UTC, crongro approved these changes
this를 좀더 잘 이해해볼 기회가 나중에 있을거에요.

다음에는 
getSize.getArea 함수가 상대적으로 크죠? 이정도이상으로 커지지 않도록 노력해보세요.

잘 개선하셨어요. 
수고했습니다. 머지해요~

2018-09-17 02:52 UTC, merged