Wfe luigi
code-squad/javascript-polygon pull request #4
Opened 2017-10-18 04:48 UTC by wfe-luigi

리뷰사항으로  수정했습니다.

2017-10-18 08:10 UTC, crongro requested changes
코멘트 확인하시고요, 
test case를 좀더 다양한 상황을 넣고 오류처리를 한번 해보실래요?

2017-10-18 08:10 UTC, nigayo commented on poly2.js
> +    if(!arguments.length) needMoreArg(1);
이것보단 length값을 비교하는게 더 정확한 표현 같네요. 1보다 작다. 이렇게.

2017-10-18 08:10 UTC, nigayo commented on poly2.js
> +function needMoreArg(arg){
함수가 수행하는 걸 이름으로 하세요.
printErrMsg 같은게 더 나을 듯.

2017-10-18 08:10 UTC, nigayo commented on poly2.js
> +    needMoreArg(3);
이코드를 이해하고 위에 코드를 수정해보세요.

(function(a,b,c) {
  if(a&b&c) console.log("ok");
  else console.log("oh..");
})(1,null,undefined);

2017-10-18 16:23 UTC, wfe-luigi commented on poly2.js
> +function needMoreArg(arg){
네

2017-10-18 16:23 UTC, wfe-luigi commented on poly2.js
> +    if(!arguments.length) needMoreArg(1);
네

2017-10-19 03:33 UTC, crongro approved these changes

2017-10-19 03:33 UTC, nigayo commented on poly2.js
> +    else if(bottom <= 0){ console.log("0보다 큰 bottom값을 입력해주세요"); }
나중에 에러메시지는 따로 묶어서 관리하는 방법(object와 배열을 사용해서)을 고민해보세요.

2017-10-19 05:52 UTC, merged