Hannarita/다각형의 넓이 구하는 함수 만들기 완료
code-squad/javascript-polygon pull request #5
Opened 2017-11-14 05:40 UTC by hannarita

2017-11-14 06:39 UTC, crongro commented
랩의 커밋로그를 참고해서 비슷하게 해보시면 좋겠어요.
좋은 커밋은 무엇인가 공부해보셔도 좋겠고요.

2017-11-14 06:42 UTC, crongro requested changes
참고해서 수정해보세요.

2017-11-14 06:42 UTC, nigayo commented on index.js
> +function circleSize(rad) {
함수이름은 동사+명사형태로 수정하세요. 즉 무엇을하다가 잘 표현되게.

2017-11-14 06:42 UTC, nigayo commented on index.js
> +function circleSize(rad) {
rad 보다는 정확한 전체 명사를 쓰세요. 읽기 좋게요.

2017-11-14 06:42 UTC, nigayo commented on index.js
> +    if(typeof rad === 'string'){
typeof 가 타입을 체크하는데 가진 한계가 있는데요.
이를 찾아서 마크다운 형식으로 정리해볼래요?

2017-11-14 06:42 UTC, nigayo commented on index.js
> +        var size = rad * rad * Math.PI;
함수 윗부분에 
var size=0;을 미리 선언해두고 여기서는 
size = rad * rad * Math.PI로 적어둬도 좋아요.

이와 관련된 학습은 호이스팅 개념입니다.

2017-11-14 06:42 UTC, nigayo commented on index.js
> +        console.log('숫자형타입만 계산이 가능합니다');
이대로라면 배열이나 다른 타입이 들어가면 어떻게 처리되나요?

2017-11-14 06:42 UTC, nigayo commented on index.js
> +    if(arguments.length<=2){
arguments 를 쓴 이유가 뭐에요?

2017-11-15 01:27 UTC, hannarita commented on index.js
> +    if(arguments.length<=2){
인자의 개수를 세고 싶어서 썼습니다

2017-11-15 01:27 UTC, hannarita commented on index.js
> +        console.log('숫자형타입만 계산이 가능합니다');
조건을 타입이 넘버가 아니면 실행되게 변경했습니당

2017-11-15 07:31 UTC, crongro approved these changes
참고해서 수정해보시고, 다음 단계 풀어보세요

2017-11-15 07:31 UTC, nigayo commented on index.js
> +        console.log('3개의 인자가 필요합니다');
의도적으로 인자체크를 시도한 건 좋아요. 
반드시 해야 하는 건 아닙니다. 

그리고, 이미 getArea에서 인자를 3개 지정해서 넘겨주는데요. 여기서 이렇게 체크하는 게 맞을까요?

2017-11-15 07:32 UTC, merged