Step1
code-squad/javascript-polygon pull request #51
Opened 2019-04-08 08:38 UTC by bestdevhyo1225

Nailer & hydol
다각형 넓이 구하기 미션

2019-04-08 09:06 UTC, crongro requested changes
async함수 잘 구현했네요.
잘하셨어요.

리뷰 드린 거 조금만 더 수정해보세요!

2019-04-08 09:06 UTC, nigayo commented on main.js
> +(main = async () => {
즉시실행함수를 사용했네요.
그런데 즉시실행함수는 함수이름이 필요할까요?

2019-04-08 09:06 UTC, nigayo commented on main.js
> +    var square = polygon.square(await input('square height'),
var를 쓰지 않아도 되겠죠?

2019-04-08 09:06 UTC, nigayo commented on main.js
> +    var cylinder = polygon.cylinder(await input('cylinder radius'),
async/await는 좀 어려운 개념인데 아무튼 잘 사용했어요.
비동기를 다루게 되면 그때 더 이해하셔도 좋겠네요.

2019-04-08 09:06 UTC, nigayo commented on polygon.js
> +    if (!checkNumber(height) || !checkNumber(underWidth) || !checkNumber(upperWidth)) {
3개를 한번에 하는 방법은 없을까요?

2019-04-08 11:47 UTC, bestdevhyo1225 commented on main.js
> +    var cylinder = polygon.cylinder(await input('cylinder radius'),
비동기 개념과 async / await 에 대해서 좀 더 심도있게 공부하겠습니다 ㅎㅎ

2019-04-08 11:47 UTC, bestdevhyo1225 commented on polygon.js
> +    if (!checkNumber(height) || !checkNumber(underWidth) || !checkNumber(upperWidth)) {
고민해보겠습니다.. 감사합니다!

2019-04-08 11:51 UTC, bestdevhyo1225 commented on main.js
> +(main = async () => {
아! 그렇군요.. 감사합니다!

2019-04-08 11:53 UTC, bestdevhyo1225 commented on main.js
> +    var square = polygon.square(await input('square height'),
네 감사합니다~!

2019-04-09 05:20 UTC, nigayo commented
https://github.com/code-squad/javascript-polygon/pull/69/files

여기 step2-2를 보냈기때문에, 지금 이 PR은 close할게요.

2019-04-09 05:20 UTC, closed without merging