Q
code-squad/javascript-polygon pull request #71
Opened 2019-04-09 05:49 UTC by park78951

2nd revision:
파라미터 체크 함수 재사용 수정

2019-04-09 06:27 UTC, nigayo commented
@park78951  코드 충돌 해결해서 다시 push해주세요.

2019-04-09 08:36 UTC, park78951 commented
코드 충돌 해결해서 다시 request 드렸습니다.
확인해주세요~

2019-04-09 08:57 UTC, crongro requested changes
수고했어요.
중요한 기능을 모두 잘 수행 했네요.
몇 개 조금 수정하고 가면 좋겠습니다.

2019-04-09 08:57 UTC, nigayo commented on areas.js
> +        area = 2 * AC + 2 * Math.PI * r * h;
코드를 보면 의도가 잘 보여야 하는데요.
뭔지는 알겠지만, AC라는 이름도 뭔지 잘 모르겠고, 2가 두 번 곱해지는 이유도 알기 좀 어렵네요.
좀더 의도를 잘 드러내는 코드로 바꿔보실래요?

2019-04-09 08:57 UTC, nigayo commented on areas.js
> +                if (arr.length !== 2) {
2,3을 여기서 체크하지 말고, 
checkParams에 보낼때 보내는쪽에서 정상값을 넣어주는 건 어때요?

2019-04-09 10:39 UTC, crongro requested changes
설명을 좀 길게 한 리뷰가 하나 있는데, 그부분을 중점적으로 개선해볼래요!

2019-04-09 10:39 UTC, nigayo commented on areas.js
> +    function checkParams(polygon, paramNum){
함수가 가진 역할을 정확히 하고, 불필요한 중복을 없애는 게 좋습니다.

여기의 switch문을 없애고요,
바깥에서 하고 있는 throw를 이곳으로 가져와서, 에러처리에 대한 책임을 여기서 다 갖는게 어떨까요? 

그리고 'circle' 은 1개가필요해! 이런정의는 checkParams에서하지 않고,
checkParams 에서 인자로 받아서 처리하고요.

2019-04-09 11:02 UTC, park78951 commented on areas.js
> +    function checkParams(polygon, paramNum){
이 전 정상값을 넣어주라고 설명해 주신 부분을 정확하게 이해 못해서 어정쩡하게 수정해서 드렸었네요... 리뷰해주신 부분 적용해서 간결하게 수정했습니다.

2019-04-10 06:07 UTC, crongro approved these changes
잘 수정하셨고요.
다음 스텝에서는 변수명도 의미있게 해보세요 !

2019-04-10 06:07 UTC, merged