step2-2 YM
code-squad/javascript-polygon pull request #78
Opened 2019-04-09 07:43 UTC by ymink16

YM & TUNA

다각형의 넓이 - 함수구현

2019-04-09 09:32 UTC, crongro requested changes
수고하셨어요.

리뷰남겨드린 것만 보완하면 좋겠습니다.

2019-04-09 09:32 UTC, nigayo commented on areaCalculator.js
> +let result1 = "계산수행순서 : ";
전역공간에 코드를 그대로 두지 않는 게 좋습니다.(이유는 차차 느껴보실 수 있을거에요)
여기 아래 부분도 함수안으로 이동~

2019-04-09 09:32 UTC, nigayo commented on cal.js
> +let getSquareArea = function(width, height) {
arrow function도 있으니 참고하세요.

함수표현식에서 const가 좀더 나을 거 같은데, 왜 그런지 두 개의 차이를 알아보고, 고민해보세요.

2019-04-09 09:32 UTC, nigayo commented on cal.js
> +let getCircleArea = function(r) {
칼닷제이에스 파일의 코드는 좋네요~!

2019-04-12 03:29 UTC, ymink16 commented on areaCalculator.js
> +let result1 = "계산수행순서 : ";
제가 실수로 printExecutionSequence()함수를 사용하지 않고 이 내용들을 전역공간 밖에 두어서 이렇게 된거 같습니다. 수정했습니다~

2019-04-12 03:29 UTC, ymink16 commented on cal.js
> +let getSquareArea = function(width, height) {
넵!! 수정했습니다

2019-04-12 05:00 UTC, honux77 commented
👍 머지합니다.

2019-04-12 06:51 UTC, merged