Step2-2 mission
code-squad/javascript-polygon pull request #79
Opened 2019-04-09 07:49 UTC by sonypark

H & Sony

다각형의 넓이 - 함수 구현

저희는 Step2-1 미션에서 했던 대로 콘솔창에서 사용자의 입력을 받아 함수를 호출하는 방식으로 구현했습니다.

2019-04-09 09:48 UTC, crongro requested changes
리뷰드린 것 수정해보세요.
getArea메서드 수정이 가장 필수입니다.

2019-04-09 09:48 UTC, nigayo commented on mission2-2/main.js
> +               if (!Number(args[i])) {
그런데 이것도 true긴하죠..
Number('3');

2019-04-09 09:48 UTC, nigayo commented on mission2-2/main.js
> +               if (!Number(args[i])) {
try-catch로 모든 에러처리를 꼭 하진 않아요.
하지만 그 사용법은 지금처럼  잘 익혀두고, 에러가 생길거 같은 부분에서 유용하게 쓰게 될 겁니다.


지금코드의 목적을 그대로 간단히 달성할 수는 있겠죠.
```javascript
function run(args) {
        if (!Number(args[0])) { 
            console.log('숫자만 입력하세요.');
            return;
       }
}
```

2019-04-09 09:48 UTC, nigayo commented on mission2-2/main.js
> +               } else {
에러를 별도 함수로 분리하시고(1)
에러를 먼저 빨리체크해서 if-else문을 줄이는 걸 시도해보세요.

2019-04-09 09:48 UTC, nigayo commented on mission2-2/main.js
> +          var inputArray = input.split(',')
const/let을 사용해보세요.

2019-04-09 09:48 UTC, nigayo commented on mission2-2/main.js
> +function getArea() {
자 getArea를 작은 크기의 함수로 만들어야 할거 같습니다.
고민하시고, 설계-개발을 다시 해보세요.

2019-04-09 09:48 UTC, nigayo commented on mission2-2/module/areaPolygon.js
> +module.exports.areaOfTrapezoid = (args) => {
요 함수의 변수명만, 의미있게 제대로 지어보실래요?

2019-04-09 09:55 UTC, sonypark commented on mission2-2/main.js
> +function getArea() {
네 알겠습니다. 콘솔로 사용자 입력을 받아 출력하려고 하다 좀 꼬인 것 같습니다. 처음부터 다시 구현해야 해보겠습니다.

2019-04-09 09:57 UTC, sonypark commented on mission2-2/main.js
> +               } else {
네 해보겠습니다!

2019-04-10 02:30 UTC, sonypark commented
H & Sony

1. 피드백 반영하여 다시 구현했습니다.
2. 추가 미션 중 하나인 printExecutionSequence 함수를 수정하였습니다.

2019-04-10 06:24 UTC, crongro approved these changes
수고했어요.
승인/머지할게요.

2019-04-10 06:24 UTC, nigayo commented on mission2-2/module/AreaOfPolygon.js
> +    checkErrors.checkNumber(arguments)            // 뒤에서 인자값이 1개인지 2개인지 확인하기 때문에
여기 checkxxx 함수 두개를 처리하는 또 다른 함수를 새로 만들 수도 있어요.
그럼 여기서 에러처리하는 코드는 딸랑 한줄이 되겠죠.

2019-04-10 06:24 UTC, nigayo commented on mission2-2/main.js
> +    console.log(callStack)
printExecutionSequence 이 코드는 그대로 인거 같아요!?
나중에 직접 보여주세요 ㅎㅎ

2019-04-10 06:24 UTC, merged

2019-04-10 06:58 UTC, sonypark commented on mission2-2/module/AreaOfPolygon.js
> +    checkErrors.checkNumber(arguments)            // 뒤에서 인자값이 1개인지 2개인지 확인하기 때문에
아..! 그러네요!!! 모듈로 묶을 생각만 하고 함수로 묶을 생각은 못 했네요. 피드백 반영해서 고치겠습니다!

2019-04-10 07:00 UTC, sonypark commented on mission2-2/main.js
> +    console.log(callStack)
네 직접 보여드리고 피드백 받겠습니다!