step2-2 미션 1. getArea 함수 생성
code-squad/javascript-polygon pull request #85
Opened 2019-04-09 08:53 UTC by Min-92

getArea 함수를 생성하고 swtich 중복을 피하기위해 checkparameter 함수를
변경, areaOfCircle 의 경우 인자가 하나 더 들어오면 재귀가 작동하도록
수정, 읽기힘든 변수 이름설정

2019-04-09 10:16 UTC, crongro requested changes
몇 개 리뷰 남겨드렸어요.
수정부탁드려요 ~

2019-04-09 10:16 UTC, nigayo commented on 2-2mission.js
> +function checkParameter(length,condition1,condition2){
length는 배열의 속성으로 많이 쓰이는 이름이라 변수명으로 잘 안쓰는 게 좋아요.

condition과 같은 이름은 나중에 객체를 사용해서 변수명을 더 개선할수는 있을거에요.

2019-04-09 10:16 UTC, nigayo commented on 2-2mission.js
> +function getArea(name,...para){
para보다는 param 이라고 하는게 일반적이에요.

2019-04-09 10:16 UTC, nigayo commented on 2-2mission.js
> +            para.forEach(function(item){
forEach편리하죠 ^^ 잘했어요.

2019-04-09 10:16 UTC, nigayo commented on 2-2mission.js
> +            checkParameter(para.length,1,2);
length는  잘 안쓴다고 말했는데요. len이라고 표현하는 것도 방법인거 같네요.

2019-04-09 10:16 UTC, nigayo commented on 2-2mission.js
> +            para.forEach(function(item){
forEach가 반복적으로 계속 보이는데요.
forEach로 돌리면서 체크하는 것을,  typeNumber함수안에서 하는 걸로 바꿔보세요.

2019-04-12 06:59 UTC, honux77 approved these changes
👍 머지합니다.

2019-04-12 06:59 UTC, merged